-- Main invoices table (UUID primary key)
CREATE TABLE IF NOT EXISTS `invoices` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `contact_id` INT NOT NULL,
    `voucher_date` DATE NOT NULL,
    `archived` BOOLEAN NOT NULL DEFAULT FALSE,
    `title` VARCHAR(255) NOT NULL DEFAULT 'Rechnung',
    `introduction` TEXT NULL,
    `remark` TEXT NULL,
    `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
    `total_net_amount` DECIMAL(10,2) NULL,
    `total_gross_amount` DECIMAL(10,2) NULL,
    `tax_type` ENUM('net','gross') NOT NULL DEFAULT 'net',
    `payment_term_label` VARCHAR(255) NULL,
    `payment_term_duration` INT NULL,
    `payment_discount_percentage` DECIMAL(5,2) NULL,
    `payment_discount_range` INT NULL,
    `shipping_date` DATE NULL,
    `shipping_type` ENUM('delivery','pickup','service') NOT NULL DEFAULT 'delivery',
    `status` ENUM('draft','ready','transmitting','transmitted','transmission_error','paid','cancelled') NOT NULL DEFAULT 'draft',
    `lex_id` VARCHAR(255) NULL,
    `lex_resource_uri` TEXT NULL,
    `lex_version` INT NOT NULL DEFAULT 0,
    `lex_created_date` TIMESTAMP NULL,
    `lex_updated_date` TIMESTAMP NULL,
    `last_error_message` TEXT NULL,
    `last_error_code` VARCHAR(50) NULL,
    `transmission_attempts` INT NOT NULL DEFAULT 0,
    `last_transmission_attempt` TIMESTAMP NULL,
    `transmitted_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uniq_lex_id` (`lex_id`),
    KEY `idx_contact_id` (`contact_id`),
    KEY `idx_status` (`status`),
    KEY `idx_voucher_date` (`voucher_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;